-- -------------------------------------------------------------
-- 
-- File Name: /u/home/eraguzin/matlab/LNspec/matlab/codegen/average__instance_P1_/hdlsrc/average_instance_P1_fixpt.vhd
-- Created: 2023-01-18 13:53:23
-- 
-- Generated by MATLAB 9.12, MATLAB Coder 5.4 and HDL Coder 3.20
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- outpk                         ce_out        1
-- outbin                        ce_out        1
-- ready_out                     ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: average_instance_P1_fixpt
-- Source Path: average__instance_P1__fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY average_instance_P1_fixpt IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        ch1_val_re                        :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En7
        ch1_val_im                        :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En7
        ch2_val_re                        :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En7
        ch2_val_im                        :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En7
        count                             :   IN    std_logic_vector(12 DOWNTO 0);  -- ufix13
        ready_in                          :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        outpk                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32_E15
        outbin                            :   OUT   std_logic_vector(10 DOWNTO 0);  -- ufix11
        ready_out                         :   OUT   std_logic
        );
END average_instance_P1_fixpt;


ARCHITECTURE rtl OF average_instance_P1_fixpt IS

  -- Component Declarations
  COMPONENT SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;  -- ufix1
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          rd_dout                         :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SimpleDualPortRAM_generic
    USE ENTITY work.SimpleDualPortRAM_generic(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL stateControl_1                   : std_logic;
  SIGNAL enb_gated                        : std_logic;
  SIGNAL ticktock                         : std_logic;
  SIGNAL tmp                              : std_logic;
  SIGNAL tmp_1                            : std_logic;
  SIGNAL ticktock_1                       : std_logic;
  SIGNAL ticktock_last_value              : std_logic;
  SIGNAL tmp_2                            : std_logic;
  SIGNAL count_unsigned                   : unsigned(12 DOWNTO 0);  -- ufix13
  SIGNAL tmp_3                            : std_logic;
  SIGNAL tmp_4                            : std_logic;
  SIGNAL tmp_5                            : std_logic;  -- ufix1
  SIGNAL tmp_6                            : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Nac                              : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL stateControl_3                   : std_logic;
  SIGNAL enb_gated_1                      : std_logic;
  SIGNAL Nac_1                            : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL tmp_7                            : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL tmp_8                            : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Nac_2                            : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL tmp_9                            : std_logic;
  SIGNAL tmp_10                           : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Nac_3                            : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Nac_last_value                   : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL tmp_11                           : std_logic;
  SIGNAL tmp_12                           : std_logic;
  SIGNAL tmp_13                           : std_logic;
  SIGNAL outpk_1                          : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL outpk_2                          : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL to2val                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_14                           : std_logic;
  SIGNAL tmp_15                           : std_logic;
  SIGNAL ctr_0_sig                        : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL lastCycle                        : std_logic;
  SIGNAL val                              : unsigned(31 DOWNTO 0);  -- ufix32_E14
  SIGNAL addr                             : signed(31 DOWNTO 0);  -- int32
  SIGNAL stateControl_5                   : std_logic;
  SIGNAL to2adr                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_16                           : unsigned(13 DOWNTO 0);  -- ufix14_En1
  SIGNAL c_9                              : unsigned(13 DOWNTO 0);  -- ufix14_En1
  SIGNAL tmp_17                           : unsigned(14 DOWNTO 0);  -- ufix15_En1
  SIGNAL tmp_18                           : unsigned(14 DOWNTO 0);  -- ufix15_En1
  SIGNAL tmp_19                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_20                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL enb_gated_2                      : std_logic;
  SIGNAL tmp_21                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL to2adr_1                         : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL to2adr_2                         : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL to2adr_last_value                : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_22                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_23                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_24                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL indexLogic_fixptsig              : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL tmp_25                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_26                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL addr_1                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_27                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL indexLogic_fixptsig_1            : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL stateControl_7                   : std_logic;
  SIGNAL tmp_28                           : unsigned(31 DOWNTO 0);  -- ufix32_E14
  SIGNAL ch1_val_re_signed                : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL ch1_val_im_signed                : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL ar                               : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL ar_1                             : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL ch2_val_re_signed                : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL ch2_val_im_signed                : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL tmp_29                           : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL p148tmp_cast                     : signed(32 DOWNTO 0);  -- sfix33_En7
  SIGNAL p148tmp_cast_1                   : signed(32 DOWNTO 0);  -- sfix33_En7
  SIGNAL y_re                             : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL y_im                             : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL br                               : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL br_1                             : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL pr1                              : signed(63 DOWNTO 0);  -- sfix64_En14
  SIGNAL ai                               : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL ai_1                             : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL bi                               : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL bi_1                             : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL pr2                              : signed(63 DOWNTO 0);  -- sfix64_En14
  SIGNAL ar_2                             : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL bi_2                             : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL pi1                              : signed(63 DOWNTO 0);  -- sfix64_En14
  SIGNAL ai_2                             : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL br_2                             : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL pi2                              : signed(63 DOWNTO 0);  -- sfix64_En14
  SIGNAL pr1_1                            : signed(63 DOWNTO 0);  -- sfix64_En14
  SIGNAL pr1in                            : signed(64 DOWNTO 0);  -- sfix65_En14
  SIGNAL pr2_1                            : signed(63 DOWNTO 0);  -- sfix64_En14
  SIGNAL pr2in                            : signed(64 DOWNTO 0);  -- sfix65_En14
  SIGNAL pi1_1                            : signed(63 DOWNTO 0);  -- sfix64_En14
  SIGNAL pi1in                            : signed(64 DOWNTO 0);  -- sfix65_En14
  SIGNAL pi2_1                            : signed(63 DOWNTO 0);  -- sfix64_En14
  SIGNAL pi2in                            : signed(64 DOWNTO 0);  -- sfix65_En14
  SIGNAL pim                              : signed(64 DOWNTO 0);  -- sfix65_En14
  SIGNAL tmp_re                           : signed(64 DOWNTO 0);  -- sfix65_En14
  SIGNAL tmp_im                           : signed(64 DOWNTO 0);  -- sfix65_En14
  SIGNAL tmp_30                           : signed(96 DOWNTO 0);  -- sfix97_En47
  SIGNAL p141tmp_cast                     : signed(97 DOWNTO 0);  -- sfix98_En47
  SIGNAL tmp_31                           : unsigned(31 DOWNTO 0);  -- ufix32_E13
  SIGNAL tmp_32                           : unsigned(33 DOWNTO 0);  -- ufix34_E13
  SIGNAL enb_gated_3                      : std_logic;
  SIGNAL buf2_ram_wrenb                   : std_logic;  -- ufix1
  SIGNAL to2val_1                         : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_33                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL to2val_2                         : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_34                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_35                           : unsigned(31 DOWNTO 0);  -- ufix32_E14
  SIGNAL tmp_36                           : unsigned(31 DOWNTO 0);  -- ufix32_E14
  SIGNAL buf2                             : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL buf2_unsigned                    : unsigned(31 DOWNTO 0);  -- ufix32_E14
  SIGNAL buf2_1                           : unsigned(31 DOWNTO 0);  -- ufix32_E14
  SIGNAL buf2_last_value                  : unsigned(31 DOWNTO 0);  -- ufix32_E14
  SIGNAL tmp_37                           : unsigned(31 DOWNTO 0);  -- ufix32_E14
  SIGNAL tmp_38                           : unsigned(33 DOWNTO 0);  -- ufix34_E13
  SIGNAL tmp_39                           : unsigned(33 DOWNTO 0);  -- ufix34_E13
  SIGNAL to2val_3                         : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_40                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_41                           : std_logic;
  SIGNAL tmp_42                           : std_logic;
  SIGNAL tmp_43                           : std_logic;
  SIGNAL to1val                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_44                           : std_logic;
  SIGNAL tmp_45                           : std_logic;
  SIGNAL lastCycle_1                      : std_logic;
  SIGNAL val_1                            : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL stateControl_9                   : std_logic;
  SIGNAL to1adr                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_46                           : unsigned(13 DOWNTO 0);  -- ufix14_En1
  SIGNAL c_26                             : unsigned(13 DOWNTO 0);  -- ufix14_En1
  SIGNAL tmp_47                           : unsigned(45 DOWNTO 0);  -- ufix46_En32
  SIGNAL tmp_48                           : unsigned(45 DOWNTO 0);  -- ufix46_En32
  SIGNAL tmp_49                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_50                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL enb_gated_4                      : std_logic;
  SIGNAL tmp_51                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL to1adr_1                         : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL to1adr_2                         : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL to1adr_last_value                : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_52                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_53                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL addr_2                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_54                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL indexLogic_fixptsig_2            : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL addr_3                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_55                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_56                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_57                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL indexLogic_fixptsig_3            : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL stateControl_11                  : std_logic;
  SIGNAL tmp_58                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_59                           : unsigned(34 DOWNTO 0);  -- ufix35_E13
  SIGNAL enb_gated_5                      : std_logic;
  SIGNAL buf1_ram_wrenb                   : std_logic;  -- ufix1
  SIGNAL to1val_1                         : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_60                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL to1val_2                         : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_61                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_62                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL buf1                             : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL buf1_unsigned                    : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL buf1_1                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL buf1_last_value                  : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_63                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_64                           : unsigned(34 DOWNTO 0);  -- ufix35_E13
  SIGNAL tmp_65                           : unsigned(34 DOWNTO 0);  -- ufix35_E13
  SIGNAL to1val_3                         : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_66                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_67                           : unsigned(31 DOWNTO 0);  -- ufix32_E15
  SIGNAL tmp_68                           : std_logic;
  SIGNAL tmp_69                           : std_logic;
  SIGNAL outbin_1                         : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_70                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_71                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_72                           : std_logic;
  SIGNAL tmp_73                           : std_logic;
  SIGNAL tmp_74                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_75                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_76                           : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL outbin_tmp                       : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL tmp_77                           : std_logic;
  SIGNAL tmp_78                           : std_logic;
  SIGNAL ready_out_1                      : std_logic;
  SIGNAL ready_out_2                      : std_logic;
  SIGNAL tmp_79                           : std_logic;
  SIGNAL tmp_80                           : std_logic;
  SIGNAL tmp_81                           : std_logic;
  SIGNAL ready_out_3                      : std_logic;
  SIGNAL tmp_82                           : std_logic;
  SIGNAL tmp_83                           : std_logic;

BEGIN
  u_buf2_ram : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 12,
                 DataWidth => 32
                 )
    PORT MAP( clk => clk,
              enb => enb_gated_3,
              wr_din => std_logic_vector(tmp_36),
              wr_addr => std_logic_vector(indexLogic_fixptsig),
              wr_en => buf2_ram_wrenb,  -- ufix1
              rd_addr => std_logic_vector(indexLogic_fixptsig_1),
              rd_dout => buf2
              );

  u_buf1_ram_generic : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 11,
                 DataWidth => 32
                 )
    PORT MAP( clk => clk,
              enb => enb_gated_5,
              wr_din => std_logic_vector(tmp_62),
              wr_addr => std_logic_vector(indexLogic_fixptsig_2),
              wr_en => buf1_ram_wrenb,  -- ufix1
              rd_addr => std_logic_vector(indexLogic_fixptsig_3),
              rd_dout => buf1
              );

  stateControl_1 <= '1';

  enb_gated <= stateControl_1 AND enb;

  tmp <=  NOT ticktock;

  ticktock_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ticktock_1 <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated = '1' THEN
        ticktock_1 <= tmp_1;
      END IF;
    END IF;
  END PROCESS ticktock_reg_process;


  out0_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ticktock_last_value <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated = '1' THEN
        ticktock_last_value <= ticktock;
      END IF;
    END IF;
  END PROCESS out0_bypass_process;


  -- 'average__instance_P1__fixpt:45' else
  -- 
  -- 'average__instance_P1__fixpt:46' if (ready_in)
  -- 
  -- 'average__instance_P1__fixpt:48' else
  -- 
  -- 'average__instance_P1__fixpt:49' to2adr(:) = int16(2048/2+1);
  -- 
  -- 'average__instance_P1__fixpt:47' to2adr(:) = fi_div_by_shift(count, 1)+fi(1, 0, 1, 0, fm);
  -- 
  -- 'average__instance_P1__fixpt:72' coder.inline( 'always' );
  -- 
  -- 'average__instance_P1__fixpt:73' if isfi( a )
  -- 
  -- 'average__instance_P1__fixpt:74' nt = numerictype( a );
  -- 
  -- 'average__instance_P1__fixpt:75' fm = fimath( a );
  -- 
  -- 'average__instance_P1__fixpt:76' nt_bs = numerictype( nt.Signed, nt.WordLength + shift_len, nt.FractionLength + 
  -- shift_len )
  -- 
  -- 'average__instance_P1__fixpt:77' y = bitsra( fi( a, nt_bs, fm ), shift_len );
  
  ticktock <= ticktock_last_value WHEN stateControl_1 = '0' ELSE
      ticktock_1;

  -- 'average__instance_P1__fixpt:27' if (ready_in)
  -- 
  -- part will be replaced by preprocessor
  
  tmp_1 <= ticktock WHEN ready_in = '0' ELSE
      tmp;

  enb <= clk_enable;

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_2 <= tmp_1;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  count_unsigned <= unsigned(count);

  -- 'average__instance_P1__fixpt:62' Nac(:) = Nac - ((ready_in) & (count == fi(1, 0, 1, 0, fm)));
  
  tmp_3 <= '1' WHEN count_unsigned = to_unsigned(16#0001#, 13) ELSE
      '0';

  tmp_4 <= ready_in AND tmp_3;

  tmp_5 <= tmp_4;

  tmp_6 <= '0' & '0' & '0' & tmp_5;

  -- HDL code generation from MATLAB function: average__instance_P1__fixpt
  Nac <= to_unsigned(16#4#, 3);

  stateControl_3 <= '1';

  enb_gated_1 <= stateControl_3 AND enb;

  tmp_7 <= resize(Nac_1, 4);

  tmp_8 <= tmp_7 - tmp_6;

  Nac_2 <= tmp_8(2 DOWNTO 0);

  -- 'average__instance_P1__fixpt:63' if (Nac == fi(0, 0, 1, 0, fm))
  
  tmp_9 <= '1' WHEN Nac_2 = to_unsigned(16#0#, 3) ELSE
      '0';

  
  tmp_10 <= Nac_2 WHEN tmp_9 = '0' ELSE
      Nac;

  Nac_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Nac_3 <= to_unsigned(16#4#, 3);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated_1 = '1' THEN
        Nac_3 <= tmp_10;
      END IF;
    END IF;
  END PROCESS Nac_reg_process;


  out0_bypass_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Nac_last_value <= to_unsigned(16#0#, 3);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated_1 = '1' THEN
        Nac_last_value <= Nac_1;
      END IF;
    END IF;
  END PROCESS out0_bypass_1_process;


  
  Nac_1 <= Nac_last_value WHEN stateControl_3 = '0' ELSE
      Nac_3;

  
  tmp_11 <= '1' WHEN Nac_1 = to_unsigned(16#1#, 3) ELSE
      '0';

  tmp_12 <= tmp_11 AND ready_in;

  delayMatch_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_13 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_13 <= tmp_12;
      END IF;
    END IF;
  END PROCESS delayMatch_1_process;


  -- 'average__instance_P1__fixpt:25' outpk = fi(0, 0, 32, -15, fm);
  outpk_1 <= to_unsigned(0, 32);

  reduced_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      outpk_2 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        outpk_2 <= outpk_1;
      END IF;
    END IF;
  END PROCESS reduced_process;


  to2val <= to_unsigned(0, 32);

  
  tmp_14 <= '1' WHEN Nac_1 = to_unsigned(16#1#, 3) ELSE
      '0';

  tmp_15 <= tmp_14 AND ready_in;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 0
  ctr_0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ctr_0_sig <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        ctr_0_sig <= to_unsigned(16#00#, 8);
      END IF;
    END IF;
  END PROCESS ctr_0_process;


  
  lastCycle <= '1' WHEN ctr_0_sig = to_unsigned(16#00#, 8) ELSE
      '0';

  val <= to_unsigned(0, 32);

  addr <= to_signed(16#00000802#, 32);

  stateControl_5 <= '1';

  to2adr <= to_unsigned(16#401#, 11);

  -- 'average__instance_P1__fixpt:51' to2val(:) = buf2(to2adr)+P;
  -- 
  -- 'average__instance_P1__fixpt:32' if (ready_in)
  -- 
  -- 'average__instance_P1__fixpt:34' else
  -- 
  -- 'average__instance_P1__fixpt:35' to1adr(:) = int16(2048/2+1);
  -- 
  -- 'average__instance_P1__fixpt:33' to1adr(:) = fi_div_by_shift(count, 1)+fi(0.5, 0, 32, 32, fm);
  -- 
  -- 'average__instance_P1__fixpt:72' coder.inline( 'always' );
  -- 
  -- 'average__instance_P1__fixpt:73' if isfi( a )
  -- 
  -- 'average__instance_P1__fixpt:74' nt = numerictype( a );
  -- 
  -- 'average__instance_P1__fixpt:75' fm = fimath( a );
  -- 
  -- 'average__instance_P1__fixpt:76' nt_bs = numerictype( nt.Signed, nt.WordLength + shift_len, nt.FractionLength + 
  -- shift_len )
  -- 
  -- 'average__instance_P1__fixpt:77' y = bitsra( fi( a, nt_bs, fm ), shift_len );
  tmp_16 <= count_unsigned & '0';

  c_9 <= SHIFT_RIGHT(tmp_16, 1);

  tmp_17 <= resize(c_9, 15);

  tmp_18 <= tmp_17 + to_unsigned(16#0002#, 15);

  tmp_19 <= tmp_18(11 DOWNTO 1);

  
  tmp_20 <= to2adr WHEN ready_in = '0' ELSE
      tmp_19;

  enb_gated_2 <= stateControl_5 AND enb;

  to2adr_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      to2adr_1 <= to_unsigned(16#401#, 11);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated_2 = '1' THEN
        to2adr_1 <= tmp_21;
      END IF;
    END IF;
  END PROCESS to2adr_reg_process;


  out0_bypass_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      to2adr_last_value <= to_unsigned(16#000#, 11);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated_2 = '1' THEN
        to2adr_last_value <= to2adr_2;
      END IF;
    END IF;
  END PROCESS out0_bypass_2_process;


  
  to2adr_2 <= to2adr_last_value WHEN stateControl_5 = '0' ELSE
      to2adr_1;

  
  tmp_21 <= tmp_20 WHEN tmp_1 = '0' ELSE
      to2adr_2;

  tmp_22 <= signed(resize(tmp_21, 32));

  -- HDL code generation from MATLAB function: average__instance_P1__fixpt_trueregionp95
  tmp_23 <= tmp_22 - 1;

  
  tmp_24 <= addr WHEN tmp_1 = '0' ELSE
      tmp_23;

  indexLogic_fixptsig <= unsigned(tmp_24(11 DOWNTO 0));

  tmp_25 <= signed(resize(tmp_20, 32));

  -- HDL code generation from MATLAB function: average__instance_P1__fixpt_falseregionp130
  tmp_26 <= tmp_25 - 1;

  addr_1 <= to_signed(16#00000802#, 32);

  
  tmp_27 <= tmp_26 WHEN tmp_1 = '0' ELSE
      addr_1;

  indexLogic_fixptsig_1 <= unsigned(tmp_27(11 DOWNTO 0));

  stateControl_7 <= '1';

  -- 'average__instance_P1__fixpt:28' ticktock(:) = ~ticktock;
  tmp_28 <= to_unsigned(0, 32);

  ch1_val_re_signed <= signed(ch1_val_re);

  ch1_val_im_signed <= signed(ch1_val_im);

  ar <= ch1_val_re_signed;

  HwModeRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ar_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        ar_1 <= ar;
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;


  ch2_val_re_signed <= signed(ch2_val_re);

  ch2_val_im_signed <= signed(ch2_val_im);

  -- 'average__instance_P1__fixpt:26' P = fi(real(ch1_val*conj(ch2_val))*(fi(1/4, 0, 32, 33, fm)), 0, 32, -13, fm);
  p148tmp_cast <= resize(ch2_val_im_signed, 33);
  p148tmp_cast_1 <=  - (p148tmp_cast);
  tmp_29 <= p148tmp_cast_1(31 DOWNTO 0);

  y_re <= ch2_val_re_signed;
  y_im <= tmp_29;

  br <= y_re;

  HwModeRegister_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      br_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        br_1 <= br;
      END IF;
    END IF;
  END PROCESS HwModeRegister_1_process;


  pr1 <= ar_1 * br_1;

  ai <= ch1_val_im_signed;

  HwModeRegister_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ai_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        ai_1 <= ai;
      END IF;
    END IF;
  END PROCESS HwModeRegister_2_process;


  bi <= y_im;

  HwModeRegister_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      bi_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        bi_1 <= bi;
      END IF;
    END IF;
  END PROCESS HwModeRegister_3_process;


  pr2 <= ai_1 * bi_1;

  HwModeRegister_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ar_2 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        ar_2 <= ar;
      END IF;
    END IF;
  END PROCESS HwModeRegister_4_process;


  HwModeRegister_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      bi_2 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        bi_2 <= bi;
      END IF;
    END IF;
  END PROCESS HwModeRegister_5_process;


  pi1 <= ar_2 * bi_2;

  HwModeRegister_6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ai_2 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        ai_2 <= ai;
      END IF;
    END IF;
  END PROCESS HwModeRegister_6_process;


  HwModeRegister_7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      br_2 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        br_2 <= br;
      END IF;
    END IF;
  END PROCESS HwModeRegister_7_process;


  pi2 <= ai_2 * br_2;

  PipelineRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      pr1_1 <= to_signed(0, 64);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        pr1_1 <= pr1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  pr1in <= resize(pr1_1, 65);

  PipelineRegister_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      pr2_1 <= to_signed(0, 64);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        pr2_1 <= pr2;
      END IF;
    END IF;
  END PROCESS PipelineRegister_1_process;


  pr2in <= resize(pr2_1, 65);

  PipelineRegister_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      pi1_1 <= to_signed(0, 64);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        pi1_1 <= pi1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_2_process;


  pi1in <= resize(pi1_1, 65);

  PipelineRegister_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      pi2_1 <= to_signed(0, 64);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        pi2_1 <= pi2;
      END IF;
    END IF;
  END PROCESS PipelineRegister_3_process;


  pi2in <= resize(pi2_1, 65);

  pim <= pi1in + pi2in;

  tmp_re <= pr1in - pr2in;
  tmp_im <= pim;

  p141tmp_cast <= resize(tmp_re & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 98);
  tmp_30 <= p141tmp_cast(96 DOWNTO 0);

  tmp_31 <= unsigned(tmp_30(91 DOWNTO 60));

  tmp_32 <= resize(tmp_31, 34);

  enb_gated_3 <= stateControl_7 AND enb;

  buf2_ram_wrenb <= '1';

  
  tmp_33 <= to2val_1 WHEN tmp_15 = '0' ELSE
      to2val;

  
  tmp_34 <= tmp_33 WHEN tmp_1 = '0' ELSE
      to2val_2;

  -- 'average__instance_P1__fixpt:64' Nac(:) = 4;
  -- 
  -- HDL code generation from MATLAB function: average__instance_P1__fixpt
  to2val_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      to2val_2 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND lastCycle = '1' THEN
        to2val_2 <= tmp_34;
      END IF;
    END IF;
  END PROCESS to2val_reg_process;


  -- HDL code generation from MATLAB function: average__instance_P1__fixpt_trueregionp92
  tmp_35 <= to2val_2(30 DOWNTO 0) & '0';

  
  tmp_36 <= val WHEN tmp_1 = '0' ELSE
      tmp_35;

  buf2_unsigned <= unsigned(buf2);

  out0_bypass_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      buf2_last_value <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated_3 = '1' THEN
        buf2_last_value <= buf2_1;
      END IF;
    END IF;
  END PROCESS out0_bypass_3_process;


  
  buf2_1 <= buf2_last_value WHEN stateControl_7 = '0' ELSE
      buf2_unsigned;

  
  tmp_37 <= buf2_1 WHEN tmp_1 = '0' ELSE
      tmp_28;

  tmp_38 <= resize(tmp_37 & '0', 34);

  tmp_39 <= tmp_38 + tmp_32;

  to2val_1 <= tmp_39(33 DOWNTO 2);

  delayMatch_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      to2val_3 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        to2val_3 <= to2val_1;
      END IF;
    END IF;
  END PROCESS delayMatch_2_process;


  
  tmp_40 <= outpk_2 WHEN tmp_13 = '0' ELSE
      to2val_3;

  
  tmp_41 <= '1' WHEN Nac_1 = to_unsigned(16#1#, 3) ELSE
      '0';

  tmp_42 <= tmp_41 AND ready_in;

  delayMatch_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tmp_43 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        tmp_43 <= tmp_42;
      END IF;
    END IF;
  END PROCESS delayMatch_3_process;


  to1val <= to_unsigned(0, 32);

  
  tmp_44 <= '1' WHEN Nac_1 = to_unsigned(16#1#, 3) ELSE
      '0';

  tmp_45 <= tmp_44 AND ready_in;

  
  lastCycle_1 <= '1' WHEN ctr_0_sig = to_unsigned(16#00#, 8) ELSE
      '0';

  val_1 <= to_unsigned(0, 32);

  stateControl_9 <= '1';

  to1adr <= to_unsigned(16#401#, 11);

  -- 'average__instance_P1__fixpt:37' to1val(:) = buf1(to1adr)+P;
  -- 
  -- 'average__instance_P1__fixpt:52' value = fi(to2val, 0, 32, -15, fm);
  -- 
  -- 'average__instance_P1__fixpt:53' if (Nac == fi(1, 0, 1, 0, fm)) & (ready_in)
  -- 
  -- 'average__instance_P1__fixpt:54' outpk(:) = to2val;
  -- 
  -- 'average__instance_P1__fixpt:55' outbin(:) = count;
  tmp_46 <= count_unsigned & '0';

  c_26 <= SHIFT_RIGHT(tmp_46, 1);

  tmp_47 <= resize(c_26 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 46);

  tmp_48 <= tmp_47 + unsigned'("0000000000000010000000000000000000000000000000");

  tmp_49 <= tmp_48(42 DOWNTO 32);

  
  tmp_50 <= to1adr WHEN ready_in = '0' ELSE
      tmp_49;

  enb_gated_4 <= stateControl_9 AND enb;

  to1adr_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      to1adr_1 <= to_unsigned(16#401#, 11);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated_4 = '1' THEN
        to1adr_1 <= tmp_51;
      END IF;
    END IF;
  END PROCESS to1adr_reg_process;


  out0_bypass_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      to1adr_last_value <= to_unsigned(16#000#, 11);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated_4 = '1' THEN
        to1adr_last_value <= to1adr_2;
      END IF;
    END IF;
  END PROCESS out0_bypass_4_process;


  
  to1adr_2 <= to1adr_last_value WHEN stateControl_9 = '0' ELSE
      to1adr_1;

  
  tmp_51 <= to1adr_2 WHEN tmp_1 = '0' ELSE
      tmp_50;

  tmp_52 <= signed(resize(tmp_51, 32));

  -- HDL code generation from MATLAB function: average__instance_P1__fixpt_falseregionp85
  tmp_53 <= tmp_52 - 1;

  addr_2 <= to_signed(16#00000401#, 32);

  
  tmp_54 <= tmp_53 WHEN tmp_1 = '0' ELSE
      addr_2;

  indexLogic_fixptsig_2 <= unsigned(tmp_54(10 DOWNTO 0));

  -- 'average__instance_P1__fixpt:31' if ticktock
  addr_3 <= to_signed(16#00000401#, 32);

  tmp_55 <= signed(resize(tmp_50, 32));

  -- HDL code generation from MATLAB function: average__instance_P1__fixpt_trueregionp135
  tmp_56 <= tmp_55 - 1;

  
  tmp_57 <= addr_3 WHEN tmp_1 = '0' ELSE
      tmp_56;

  indexLogic_fixptsig_3 <= unsigned(tmp_57(10 DOWNTO 0));

  stateControl_11 <= '1';

  tmp_58 <= to_unsigned(0, 32);

  tmp_59 <= resize(tmp_31, 35);

  enb_gated_5 <= stateControl_11 AND enb;

  buf1_ram_wrenb <= '1';

  
  tmp_60 <= to1val_1 WHEN tmp_45 = '0' ELSE
      to1val;

  
  tmp_61 <= to1val_2 WHEN tmp_1 = '0' ELSE
      tmp_60;

  -- HDL code generation from MATLAB function: average__instance_P1__fixpt_falseregionp82
  to1val_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      to1val_2 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND lastCycle_1 = '1' THEN
        to1val_2 <= tmp_61;
      END IF;
    END IF;
  END PROCESS to1val_reg_process;


  
  tmp_62 <= to1val_2 WHEN tmp_1 = '0' ELSE
      val_1;

  buf1_unsigned <= unsigned(buf1);

  out0_bypass_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      buf1_last_value <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated_5 = '1' THEN
        buf1_last_value <= buf1_1;
      END IF;
    END IF;
  END PROCESS out0_bypass_5_process;


  
  buf1_1 <= buf1_last_value WHEN stateControl_11 = '0' ELSE
      buf1_unsigned;

  
  tmp_63 <= tmp_58 WHEN tmp_1 = '0' ELSE
      buf1_1;

  tmp_64 <= resize(tmp_63 & '0' & '0', 35);

  tmp_65 <= tmp_64 + tmp_59;

  to1val_1 <= tmp_65(33 DOWNTO 2);

  delayMatch_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      to1val_3 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        to1val_3 <= to1val_1;
      END IF;
    END IF;
  END PROCESS delayMatch_4_process;


  
  tmp_66 <= outpk_2 WHEN tmp_43 = '0' ELSE
      to1val_3;

  
  tmp_67 <= tmp_40 WHEN tmp_2 = '0' ELSE
      tmp_66;

  outpk <= std_logic_vector(tmp_67);

  
  tmp_68 <= '1' WHEN Nac_1 = to_unsigned(16#1#, 3) ELSE
      '0';

  tmp_69 <= tmp_68 AND ready_in;

  -- 'average__instance_P1__fixpt:24' outbin = fi(int16(0), 0, 11, 0, fm);
  outbin_1 <= to_unsigned(16#000#, 11);

  -- 'average__instance_P1__fixpt:56' to2val(:) = 0;
  -- 
  -- 'average__instance_P1__fixpt:57' ready_out(:)=true;
  -- 
  -- 'average__instance_P1__fixpt:59' buf1(to1adr) = to1val;
  -- 
  -- 'average__instance_P1__fixpt:38' if (Nac == fi(1, 0, 1, 0, fm)) & (ready_in)
  -- 
  -- 'average__instance_P1__fixpt:39' outpk(:) = to1val;
  -- 
  -- 'average__instance_P1__fixpt:40' outbin(:) = count;
  tmp_70 <= count_unsigned(10 DOWNTO 0);

  
  tmp_71 <= outbin_1 WHEN tmp_69 = '0' ELSE
      tmp_70;

  
  tmp_72 <= '1' WHEN Nac_1 = to_unsigned(16#1#, 3) ELSE
      '0';

  tmp_73 <= tmp_72 AND ready_in;

  -- 'average__instance_P1__fixpt:41' to1val(:) = 0;
  -- 
  -- 'average__instance_P1__fixpt:42' ready_out(:)=true;
  -- 
  -- 'average__instance_P1__fixpt:44' buf2(to2adr) = to2val;
  tmp_74 <= count_unsigned(10 DOWNTO 0);

  
  tmp_75 <= outbin_1 WHEN tmp_73 = '0' ELSE
      tmp_74;

  
  tmp_76 <= tmp_71 WHEN tmp_1 = '0' ELSE
      tmp_75;

  delayMatch_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      outbin_tmp <= to_unsigned(16#000#, 11);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        outbin_tmp <= tmp_76;
      END IF;
    END IF;
  END PROCESS delayMatch_5_process;


  outbin <= std_logic_vector(outbin_tmp);

  
  tmp_77 <= '1' WHEN Nac_1 = to_unsigned(16#1#, 3) ELSE
      '0';

  tmp_78 <= tmp_77 AND ready_in;

  -- 'average__instance_P1__fixpt:23' ready_out = false;
  -- 
  -- 'average__instance_P1__fixpt:12' if isempty(Nac)
  -- 
  -- 'average__instance_P1__fixpt:8' fm = get_fimath();
  -- 
  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  -- 
  --                                                                          %
  -- 
  --          Generated by MATLAB 9.12 and Fixed-Point Designer 7.4           %
  -- 
  --                                                                          %
  -- 
  -- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  ready_out_1 <= '0';

  ready_out_2 <= '1';

  
  tmp_79 <= ready_out_1 WHEN tmp_78 = '0' ELSE
      ready_out_2;

  
  tmp_80 <= '1' WHEN Nac_1 = to_unsigned(16#1#, 3) ELSE
      '0';

  tmp_81 <= tmp_80 AND ready_in;

  ready_out_3 <= '1';

  
  tmp_82 <= ready_out_1 WHEN tmp_81 = '0' ELSE
      ready_out_3;

  
  tmp_83 <= tmp_79 WHEN tmp_1 = '0' ELSE
      tmp_82;

  delayMatch_6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ready_out <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        ready_out <= tmp_83;
      END IF;
    END IF;
  END PROCESS delayMatch_6_process;


  ce_out <= clk_enable;

END rtl;

