-- -------------------------------------------------------------
-- 
-- File Name: /u/home/eraguzin/matlab/LNspec/matlab/codegen/sfft/hdlsrc/sfft_fixpt.vhd
-- Created: 2023-01-19 10:44:41
-- 
-- Generated by MATLAB 9.12, MATLAB Coder 5.4 and HDL Coder 3.20
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- fft_out_re                    ce_out        1
-- fft_out_im                    ce_out        1
-- fft_valid                     ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sfft_fixpt
-- Source Path: sfft_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY sfft_fixpt IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        c_re                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En18
        c_im                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En18
        ce_out                            :   OUT   std_logic;
        fft_out_re                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En7
        fft_out_im                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En7
        fft_valid                         :   OUT   std_logic
        );
END sfft_fixpt;


ARCHITECTURE rtl OF sfft_fixpt IS

  -- Component Declarations
  COMPONENT dsphdl_FFT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En18
          dataIn_im                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En18
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(43 DOWNTO 0);  -- sfix44_En18
          dataOut_im                      :   OUT   std_logic_vector(43 DOWNTO 0);  -- sfix44_En18
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dsphdl_FFT
    USE ENTITY work.dsphdl_FFT(rtl);

  -- Signals
  SIGNAL tmp                              : std_logic;
  SIGNAL varargout_1_re                   : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL varargout_1_im                   : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL varargout_2                      : std_logic;
  SIGNAL varargout_1_re_signed            : signed(43 DOWNTO 0);  -- sfix44_En18
  SIGNAL varargout_1_im_signed            : signed(43 DOWNTO 0);  -- sfix44_En18
  SIGNAL fft_out_re_tmp                   : signed(31 DOWNTO 0);  -- sfix32_En7
  SIGNAL fft_out_im_tmp                   : signed(31 DOWNTO 0);  -- sfix32_En7

BEGIN
  u_dsphdl_FFT : dsphdl_FFT
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn_re => c_re,  -- sfix32_En18
              dataIn_im => c_im,  -- sfix32_En18
              validIn => tmp,
              dataOut_re => varargout_1_re,  -- sfix44_En18
              dataOut_im => varargout_1_im,  -- sfix44_En18
              validOut => varargout_2
              );

  -- 'sfft_fixpt:15' [fmo_1, fmo_2] = dfft(c, true);
  tmp <= '1';

  varargout_1_re_signed <= signed(varargout_1_re);

  varargout_1_im_signed <= signed(varargout_1_im);

  -- 'sfft_fixpt:16' fft_out = fi(fmo_1, 1, 32, 7, fm);
  fft_out_re_tmp <= varargout_1_re_signed(42 DOWNTO 11);
  fft_out_im_tmp <= varargout_1_im_signed(42 DOWNTO 11);

  fft_out_re <= std_logic_vector(fft_out_re_tmp);

  fft_out_im <= std_logic_vector(fft_out_im_tmp);

  ce_out <= clk_enable;

  fft_valid <= varargout_2;

END rtl;

