vlib work
vcom  spectrometer_fixpt_pkg.vhd
vcom  SimpleDualPortRAM_generic.vhd
vcom  SDFCommutator1.vhd
vcom  RADIX22FFT_SDF1_1.vhd
vcom  RADIX22FFT_CTRL1_1.vhd
vcom  SDFCommutator2.vhd
vcom  RADIX22FFT_SDF2_2.vhd
vcom  RADIX22FFT_CTRL1_2.vhd
vcom  TWDLROM_3_1.vhd
vcom  Complex4Multiply.vhd
vcom  SDFCommutator3.vhd
vcom  RADIX22FFT_SDF1_3.vhd
vcom  RADIX22FFT_CTRL1_3.vhd
vcom  SDFCommutator4.vhd
vcom  RADIX22FFT_SDF2_4.vhd
vcom  RADIX22FFT_CTRL1_4.vhd
vcom  TWDLROM_5_1.vhd
vcom  Complex4Multiply_block.vhd
vcom  SDFCommutator5.vhd
vcom  RADIX22FFT_SDF1_5.vhd
vcom  RADIX22FFT_CTRL1_5.vhd
vcom  SDFCommutator6.vhd
vcom  RADIX22FFT_SDF2_6.vhd
vcom  RADIX22FFT_CTRL1_6.vhd
vcom  TWDLROM_7_1.vhd
vcom  Complex4Multiply_block1.vhd
vcom  SDFCommutator7.vhd
vcom  RADIX22FFT_SDF1_7.vhd
vcom  RADIX22FFT_CTRL1_7.vhd
vcom  SDFCommutator8.vhd
vcom  RADIX22FFT_SDF2_8.vhd
vcom  RADIX22FFT_CTRL1_8.vhd
vcom  TWDLROM_9_1.vhd
vcom  Complex4Multiply_block2.vhd
vcom  SDFCommutator9.vhd
vcom  RADIX22FFT_SDF1_9.vhd
vcom  RADIX22FFT_CTRL1_9.vhd
vcom  SDFCommutator10.vhd
vcom  RADIX22FFT_SDF2_10.vhd
vcom  RADIX22FFT_CTRL1_10.vhd
vcom  TWDLROM_11_1.vhd
vcom  Complex4Multiply_block3.vhd
vcom  SDFCommutator11.vhd
vcom  RADIX22FFT_SDF1_11.vhd
vcom  RADIX22FFT_CTRL1_11.vhd
vcom  SDFCommutator12.vhd
vcom  RADIX22FFT_SDF2_12.vhd
vcom  RADIX22FFT_CTRL1_12.vhd
vcom  RADIX2FFT_bitNatural.vhd
vcom  dsphdl_FFT.vhd
vcom  SimpleDualPortRAM_generic_block.vhd
vcom  spectrometer_fixpt.vhd
vcom  spectrometer_fixpt_tb_pkg.vhd
vcom  spectrometer_fixpt_tb.vhd
